version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 0
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/demo"
    schedule:
      interval: monthly
    open-pull-requests-limit: 0
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 0
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
