repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        args: [--write, --config, package.json, ./src/**]
